In [22]:
pd.set_option('display.max_rows', 1000)
import pandas as pd
import numpy as np

## Important

AREA, ANGLE and REL have missing data.

In [24]:
# Just load the dataset
dd_df = pd.read_sas("/Users/gomerudo/workspace/SAS/SASUniversityEdition/myfolders/datasetsBD/assignment_dd.sas7bdat")

dd_df['ID'] = dd_df['ID'].astype('int')
dd_df['FU'] = dd_df['FU'].astype('int')
dd_df['Hand'] = dd_df['Hand'].astype('int')
dd_df['SEX'] = dd_df['SEX'].astype('int')
dd_df['SMOKE'] = dd_df['SMOKE'].astype('int')
dd_df['ALC'] = dd_df['ALC'].astype('int')
dd_df['INJ'] = dd_df['INJ'].astype('int')
dd_df['DIA'] = dd_df['DIA'].astype('int')
dd_df['EPI'] = dd_df['EPI'].astype('int')
dd_df['LIV'] = dd_df['LIV'].astype('int')
#dd_df['REL'] = dd_df['REL'].astype('int')
dd_df['DD'] = dd_df['DD'].astype('int')

dd_df.head()

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
0,2,0,0,0.000000,0,81.0,1,1,0,0,0,0,1.0,1,3.63,0.0
1,2,0,1,0.000000,0,81.0,1,1,0,0,0,0,1.0,1,3.33,0.0
2,2,1,0,5.753425,0,81.0,1,1,0,0,0,0,1.0,1,2.57,0.0
3,2,1,1,5.753425,0,81.0,1,1,0,0,0,0,1.0,1,2.19,0.0
4,2,2,0,11.736986,0,81.0,1,1,0,0,0,0,1.0,1,2.50,0.0

In [23]:
# Fill missing values with -1, since groupby remove NaN values. 
# This way we can see how many patients with missinga data in column REL we have.

dd_df = dd_df.fillna(-1)
grouped = dd_df.groupby(['ID', 'REL'])
grouped.count()

          FU  Hand  MONTH  SEX  AGE0  SMOKE  ALC  INJ  DIA  EPI  LIV  DD  \
ID  REL
2    0.0   2     2      2    2     2      2    2    2    2    2    2   2
     1.0  18    18     18   18    18     18   18   18   18   18   18  18
3    1.0  20    20     20   20    20     20   20   20   20   20   20  20
4    1.0  16    16     16   16    16     16   16   16   16   16   16  16
6    0.0  14    14     14   14    14     14   14   14   14   14   14  14
7    0.0  20    20     20   20    20     20   20   20   20   20   20  20
8    1.0  10    10     10   10    10     10   10   10   10   10   10  10
9   -1.0   1     1      1    1     1      1    1    1    1    1    1   1
     0.0   8     8      8    8     8      8    8    8    8    8    8   8
10   0.0  12    12     12   12    12     12   12   12   12   12   12  12
11   0.0  12    12     12   12    12     12   12   12   12   12   12  12
12   0.0  14    14     14   14    14     14   14   14   14   14   14  14
     1.0   6     6      6    6     6      6    6    6    6    6    6   6
14   0.0  10    10     10   10    10     10   10   10   10   10   10  10
15   0.0   3     3      3    3     3      3    3    3    3    3    3   3
16   1.0   6     6      6    6     6      6    6    6    6    6    6   6
17   0.0   6     6      6    6     6      6    6    6    6    6    6   6
19   0.0  10    10     10   10    10     10   10   10   10   10   10  10
20  -1.0   1     1      1    1     1      1    1    1    1    1    1   1
     1.0   9     9      9    9     9      9    9    9    9    9    9   9
21   0.0   6     6      6    6     6      6    6    6    6    6    6   6
23   0.0   6     6      6    6     6      6    6    6    6    6    6   6
24   0.0  14    14     14   14    14     14   14   14   14   14   14  14
     1.0   2     2      2    2     2      2    2    2    2    2    2   2
25   0.0   4     4      4    4     4      4    4    4    4    4    4   4
26   1.0  10    10     10   10    10     10   10   10   10   10   10  10
27   1.0  18    18     18   18    18     18   18   18   18   18   18  18
28   1.0  18    18     18   18    18     18   18   18   18   18   18  18
30   0.0  20    20     20   20    20     20   20   20   20   20   20  20
31   1.0  10    10     10   10    10     10   10   10   10   10   10  10
32   0.0   6     6      6    6     6      6    6    6    6    6    6   6
     1.0  10    10     10   10    10     10   10   10   10   10   10  10
33   1.0  18    18     18   18    18     18   18   18   18   18   18  18
34   0.0  20    20     20   20    20     20   20   20   20   20   20  20
35   0.0   4     4      4    4     4      4    4    4    4    4    4   4
     1.0  16    16     16   16    16     16   16   16   16   16   16  16
36   1.0  10    10     10   10    10     10   10   10   10   10   10  10
37   0.0  10    10     10   10    10     10   10   10   10   10   10  10
38   0.0   4     4      4    4     4      4    4    4    4    4    4   4
     1.0  12    12     12   12    12     12   12   12   12   12   12  12
40   0.0  20    20     20   20    20     20   20   20   20   20   20  20
41   1.0  10    10     10   10    10     10   10   10   10   10   10  10
42   1.0  20    20     20   20    20     20   20   20   20   20   20  20
44   0.0  20    20     20   20    20     20   20   20   20   20   20  20
45   1.0  10    10     10   10    10     10   10   10   10   10   10  10
46   0.0  20    20     20   20    20     20   20   20   20   20   20  20
47   0.0  20    20     20   20    20     20   20   20   20   20   20  20
48   1.0  20    20     20   20    20     20   20   20   20   20   20  20
49   0.0   2     2      2    2     2      2    2    2    2    2    2   2
50   0.0  20    20     20   20    20     20   20   20   20   20   20  20
51   0.0  20    20     20   20    20     20   20   20   20   20   20  20
52   1.0  10    10     10   10    10     10   10   10   10   10   10  10
53   1.0  22    22     22   22    22     22   22   22   22   22   22  22
54   1.0  16    16     16   16    16     16   16   16   16   16   16  16
56   1.0  13    13     13   13    13     13   13   13   13   13   13  13
57   0.0  20    20     20   20    20     20   20   20   20   20   20  20
58   0.0  20    20     20   20    20     20   20   20   20   20   20  20
59   0.0  20    20     20   20    20     20   20   20   20   20   20  20
60   0.0   4     4      4    4     4      4    4    4    4    4    4   4
62   0.0  20    20     20   20    20     20   20   20   20   20   20  20
63   1.0  10    10     10   10    10     10   10   10   10   10   10  10
64   0.0  20    20     20   20    20     20   20   20   20   20   20  20
65   1.0   7     7      7    7     7      7    7    7    7    7    7   7
66   0.0  10    10     10   10    10     10   10   10   10   10   10  10
67   0.0  18    18     18   18    18     18   18   18   18   18   18  18
     1.0   2     2      2    2     2      2    2    2    2    2    2   2
68   0.0  14    14     14   14    14     14   14   14   14   14   14  14
70   0.0  20    20     20   20    20     20   20   20   20   20   20  20
71   0.0  20    20     20   20    20     20   20   20   20   20   20  20
72   0.0  20    20     20   20    20     20   20   20   20   20   20  20
73   0.0  18    18     18   18    18     18   18   18   18   18   18  18
74   0.0   5     5      5    5     5      5    5    5    5    5    5   5
75   0.0   6     6      6    6     6      6    6    6    6    6    6   6
76   0.0   2     2      2    2     2      2    2    2    2    2    2   2
78   0.0  12    12     12   12    12     12   12   12   12   12   12  12
79   0.0  20    20     20   20    20     20   20   20   20   20   20  20
80   1.0  14    14     14   14    14     14   14   14   14   14   14  14
81   0.0   2     2      2    2     2      2    2    2    2    2    2   2
82   0.0  20    20     20   20    20     20   20   20   20   20   20  20
83   1.0  10    10     10   10    10     10   10   10   10   10   10  10
84   0.0  19    19     19   19    19     19   19   19   19   19   19  19
85   0.0   5     5      5    5     5      5    5    5    5    5    5   5
     1.0   6     6      6    6     6      6    6    6    6    6    6   6
86   1.0  11    11     11   11    11     11   11   11   11   11   11  11
87   1.0  10    10     10   10    10     10   10   10   10   10   10  10
88   0.0  20    20     20   20    20     20   20   20   20   20   20  20
90   1.0   6     6      6    6     6      6    6    6    6    6    6   6
92   1.0   4     4      4    4     4      4    4    4    4    4    4   4
93   0.0   4     4      4    4     4      4    4    4    4    4    4   4
     1.0   6     6      6    6     6      6    6    6    6    6    6   6
94   0.0  20    20     20   20    20     20   20   20   20   20   20  20
95   1.0  22    22     22   22    22     22   22   22   22   22   22  22
96   1.0  10    10     10   10    10     10   10   10   10   10   10  10
97   1.0   7     7      7    7     7      7    7    7    7    7    7   7
98   0.0  14    14     14   14    14     14   14   14   14   14   14  14
100  1.0  10    10     10   10    10     10   10   10   10   10   10  10
101  1.0   5     5      5    5     5      5    5    5    5    5    5   5
102  1.0  18    18     18   18    18     18   18   18   18   18   18  18
103  1.0  20    20     20   20    20     20   20   20   20   20   20  20
104  0.0   2     2      2    2     2      2    2    2    2    2    2   2
     1.0  18    18     18   18    18     18   18   18   18   18   18  18
105  0.0   4     4      4    4     4      4    4    4    4    4    4   4
107  0.0   4     4      4    4     4      4    4    4    4    4    4   4
108  0.0   2     2      2    2     2      2    2    2    2    2    2   2
     1.0  18    18     18   18    18     18   18   18   18   18   18  18
109  1.0   9     9      9    9     9      9    9    9    9    9    9   9
110  0.0  10    10     10   10    10     10   10   10   10   10   10  10
111  0.0  10    10     10   10    10     10   10   10   10   10   10  10
112  1.0   9     9      9    9     9      9    9    9    9    9    9   9
113  1.0   4     4      4    4     4      4    4    4    4    4    4   4
114  1.0  11    11     11   11    11     11   11   11   11   11   11  11
115  0.0  10    10     10   10    10     10   10   10   10   10   10  10
116  0.0  20    20     20   20    20     20   20   20   20   20   20  20
117  0.0   9     9      9    9     9      9    9    9    9    9    9   9
119  0.0  16    16     16   16    16     16   16   16   16   16   16  16
120  0.0  18    18     18   18    18     18   18   18   18   18   18  18
121  0.0   3     3      3    3     3      3    3    3    3    3    3   3
123  0.0  10    10     10   10    10     10   10   10   10   10   10  10
124  1.0  10    10     10   10    10     10   10   10   10   10   10  10
125  1.0  24    24     24   24    24     24   24   24   24   24   24  24
126  0.0   8     8      8    8     8      8    8    8    8    8    8   8
127  1.0  20    20     20   20    20     20   20   20   20   20   20  20
128  0.0   4     4      4    4     4      4    4    4    4    4    4   4
130  0.0   8     8      8    8     8      8    8    8    8    8    8   8
     1.0  12    12     12   12    12     12   12   12   12   12   12  12
131  1.0  20    20     20   20    20     20   20   20   20   20   20  20
132  0.0  20    20     20   20    20     20   20   20   20   20   20  20
134  0.0   9     9      9    9     9      9    9    9    9    9    9   9
135  0.0   6     6      6    6     6      6    6    6    6    6    6   6
136  0.0  20    20     20   20    20     20   20   20   20   20   20  20
137  1.0  16    16     16   16    16     16   16   16   16   16   16  16
138  0.0  20    20     20   20    20     20   20   20   20   20   20  20
139  1.0  10    10     10   10    10     10   10   10   10   10   10  10
140  0.0  18    18     18   18    18     18   18   18   18   18   18  18
141  1.0   4     4      4    4     4      4    4    4    4    4    4   4
142  0.0  10    10     10   10    10     10   10   10   10   10   10  10
143  1.0   9     9      9    9     9      9    9    9    9    9    9   9
145  0.0  18    18     18   18    18     18   18   18   18   18   18  18
146  0.0   2     2      2    2     2      2    2    2    2    2    2   2
147  1.0   8     8      8    8     8      8    8    8    8    8    8   8
148  1.0  10    10     10   10    10     10   10   10   10   10   10  10
149  0.0  18    18     18   18    18     18   18   18   18   18   18  18
150  0.0  18    18     18   18    18     18   18   18   18   18   18  18
151 -1.0   2     2      2    2     2      2    2    2    2    2    2   2
     0.0  14    14     14   14    14     14   14   14   14   14   14  14
152  0.0  16    16     16   16    16     16   16   16   16   16   16  16
153  1.0  15    15     15   15    15     15   15   15   15   15   15  15
154  0.0   2     2      2    2     2      2    2    2    2    2    2   2
     1.0   1     1      1    1     1      1    1    1    1    1    1   1
156  1.0  16    16     16   16    16     16   16   16   16   16   16  16
157  0.0  20    20     20   20    20     20   20   20   20   20   20  20
158  0.0  20    20     20   20    20     20   20   20   20   20   20  20
159  1.0  20    20     20   20    20     20   20   20   20   20   20  20
160  0.0   6     6      6    6     6      6    6    6    6    6    6   6
161  1.0  12    12     12   12    12     12   12   12   12   12   12  12
162  1.0   6     6      6    6     6      6    6    6    6    6    6   6
164  1.0  13    13     13   13    13     13   13   13   13   13   13  13
165  1.0  11    11     11   11    11     11   11   11   11   11   11  11
166  1.0   5     5      5    5     5      5    5    5    5    5    5   5
167  0.0  10    10     10   10    10     10   10   10   10   10   10  10
168  0.0   6     6      6    6     6      6    6    6    6    6    6   6
     1.0   2     2      2    2     2      2    2    2    2    2    2   2
170  0.0  18    18     18   18    18     18   18   18   18   18   18  18
171  1.0  10    10     10   10    10     10   10   10   10   10   10  10
172  0.0  20    20     20   20    20     20   20   20   20   20   20  20
173  1.0  20    20     20   20    20     20   20   20   20   20   20  20
174 -1.0   1     1      1    1     1      1    1    1    1    1    1   1
     0.0  10    10     10   10    10     10   10   10   10   10   10  10
177 -1.0   4     4      4    4     4      4    4    4    4    4    4   4
     0.0   2     2      2    2     2      2    2    2    2    2    2   2
     1.0   3     3      3    3     3      3    3    3    3    3    3   3
178  1.0   9     9      9    9     9      9    9    9    9    9    9   9
179 -1.0   8     8      8    8     8      8    8    8    8    8    8   8
     0.0  10    10     10   10    10     10   10   10   10   10   10  10
     1.0   2     2      2    2     2      2    2    2    2    2    2   2
180  0.0  20    20     20   20    20     20   20   20   20   20   20  20
182  0.0   2     2      2    2     2      2    2    2    2    2    2   2
     1.0  18    18     18   18    18     18   18   18   18   18   18  18
183 -1.0   2     2      2    2     2      2    2    2    2    2    2   2
     0.0   6     6      6    6     6      6    6    6    6    6    6   6
184  1.0   7     7      7    7     7      7    7    7    7    7    7   7
185  1.0  14    14     14   14    14     14   14   14   14   14   14  14
186  0.0   8     8      8    8     8      8    8    8    8    8    8   8
187  0.0  10    10     10   10    10     10   10   10   10   10   10  10
188  1.0  10    10     10   10    10     10   10   10   10   10   10  10
189  0.0  20    20     20   20    20     20   20   20   20   20   20  20
190  1.0   8     8      8    8     8      8    8    8    8    8    8   8
191  1.0   9     9      9    9     9      9    9    9    9    9    9   9
193  1.0  14    14     14   14    14     14   14   14   14   14   14  14
195  1.0  10    10     10   10    10     10   10   10   10   10   10  10
196  0.0  18    18     18   18    18     18   18   18   18   18   18  18
197  0.0  20    20     20   20    20     20   20   20   20   20   20  20
198  1.0   2     2      2    2     2      2    2    2    2    2    2   2
199  0.0  10    10     10   10    10     10   10   10   10   10   10  10
200  0.0   1     1      1    1     1      1    1    1    1    1    1   1
201  1.0   8     8      8    8     8      8    8    8    8    8    8   8
202  0.0  12    12     12   12    12     12   12   12   12   12   12  12
203  0.0   2     2      2    2     2      2    2    2    2    2    2   2
205  0.0  10    10     10   10    10     10   10   10   10   10   10  10
206  1.0   4     4      4    4     4      4    4    4    4    4    4   4
207  0.0   6     6      6    6     6      6    6    6    6    6    6   6
208  1.0  18    18     18   18    18     18   18   18   18   18   18  18
209  0.0  10    10     10   10    10     10   10   10   10   10   10  10
210  0.0  10    10     10   10    10     10   10   10   10   10   10  10
212  1.0  18    18     18   18    18     18   18   18   18   18   18  18
213  1.0  10    10     10   10    10     10   10   10   10   10   10  10
214  0.0  10    10     10   10    10     10   10   10   10   10   10  10
215  0.0   8     8      8    8     8      8    8    8    8    8    8   8
216  1.0  20    20     20   20    20     20   20   20   20   20   20  20
218  0.0   3     3      3    3     3      3    3    3    3    3    3   3
     1.0   7     7      7    7     7      7    7    7    7    7    7   7
219  0.0   6     6      6    6     6      6    6    6    6    6    6   6
220  0.0  13    13     13   13    13     13   13   13   13   13   13  13
221  0.0   8     8      8    8     8      8    8    8    8    8    8   8
     1.0   5     5      5    5     5      5    5    5    5    5    5   5
223  0.0   8     8      8    8     8      8    8    8    8    8    8   8
     1.0   4     4      4    4     4      4    4    4    4    4    4   4
224  1.0  17    17     17   17    17     17   17   17   17   17   17  17
225  1.0   2     2      2    2     2      2    2    2    2    2    2   2
226  0.0  20    20     20   20    20     20   20   20   20   20   20  20
227  1.0  12    12     12   12    12     12   12   12   12   12   12  12
228  1.0  10    10     10   10    10     10   10   10   10   10   10  10
229  1.0  20    20     20   20    20     20   20   20   20   20   20  20
230  0.0  20    20     20   20    20     20   20   20   20   20   20  20
231  0.0  20    20     20   20    20     20   20   20   20   20   20  20
232  0.0  20    20     20   20    20     20   20   20   20   20   20  20
233  0.0  20    20     20   20    20     20   20   20   20   20   20  20
234  1.0   9     9      9    9     9      9    9    9    9    9    9   9
235  0.0   6     6      6    6     6      6    6    6    6    6    6   6
     1.0  14    14     14   14    14     14   14   14   14   14   14  14
236  1.0   2     2      2    2     2      2    2    2    2    2    2   2
237  0.0   8     8      8    8     8      8    8    8    8    8    8   8
     1.0  10    10     10   10    10     10   10   10   10   10   10  10
239  1.0   6     6      6    6     6      6    6    6    6    6    6   6
240  0.0  20    20     20   20    20     20   20   20   20   20   20  20
241  0.0  18    18     18   18    18     18   18   18   18   18   18  18
242  0.0   2     2      2    2     2      2    2    2    2    2    2   2
243 -1.0   1     1      1    1     1      1    1    1    1    1    1   1
     0.0   9     9      9    9     9      9    9    9    9    9    9   9
244  1.0  10    10     10   10    10     10   10   10   10   10   10  10
245  1.0  15    15     15   15    15     15   15   15   15   15   15  15
246  0.0   8     8      8    8     8      8    8    8    8    8    8   8
247  0.0   4     4      4    4     4      4    4    4    4    4    4   4
     1.0   4     4      4    4     4      4    4    4    4    4    4   4
248  0.0   4     4      4    4     4      4    4    4    4    4    4   4
     1.0   2     2      2    2     2      2    2    2    2    2    2   2
249  0.0  18    18     18   18    18     18   18   18   18   18   18  18
250  0.0  10    10     10   10    10     10   10   10   10   10   10  10
251  0.0  10    10     10   10    10     10   10   10   10   10   10  10
252  1.0   9     9      9    9     9      9    9    9    9    9    9   9
253  0.0   4     4      4    4     4      4    4    4    4    4    4   4
254  0.0  20    20     20   20    20     20   20   20   20   20   20  20
255  0.0   8     8      8    8     8      8    8    8    8    8    8   8
256  0.0  20    20     20   20    20     20   20   20   20   20   20  20
257  0.0   6     6      6    6     6      6    6    6    6    6    6   6
258  0.0   4     4      4    4     4      4    4    4    4    4    4   4

          AREA  ANGLE
ID  REL
2    0.0     2      2
     1.0    18     18
3    1.0    20     20
4    1.0    16     16
6    0.0    14     14
7    0.0    20     20
8    1.0    10     10
9   -1.0     1      1
     0.0     8      8
10   0.0    12     12
11   0.0    12     12
12   0.0    14     14
     1.0     6      6
14   0.0    10     10
15   0.0     3      3
16   1.0     6      6
17   0.0     6      6
19   0.0    10     10
20  -1.0     1      1
     1.0     9      9
21   0.0     6      6
23   0.0     6      6
24   0.0    14     14
     1.0     2      2
25   0.0     4      4
26   1.0    10     10
27   1.0    18     18
28   1.0    18     18
30   0.0    20     20
31   1.0    10     10
32   0.0     6      6
     1.0    10     10
33   1.0    18     18
34   0.0    20     20
35   0.0     4      4
     1.0    16     16
36   1.0    10     10
37   0.0    10     10
38   0.0     4      4
     1.0    12     12
40   0.0    20     20
41   1.0    10     10
42   1.0    20     20
44   0.0    20     20
45   1.0    10     10
46   0.0    20     20
47   0.0    20     20
48   1.0    20     20
49   0.0     2      2
50   0.0    20     20
51   0.0    20     20
52   1.0    10     10
53   1.0    22     22
54   1.0    16     16

In [69]:
dd_df = dd_df.fillna(-1)

filtered1 = dd_df[dd_df['AREA'] < 0]
filtered1

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
103,9,2,1,17.753425,0,59.0,1,1,0,0,0,0,-1.0,1,-1.0,-1.0
1020,85,8,0,45.961644,0,60.0,1,1,0,0,0,0,1.0,1,-1.0,-1.0
1141,97,5,0,35.802740,1,57.0,0,1,1,0,0,0,1.0,1,-1.0,-1.0
1992,174,8,0,45.928767,0,67.0,1,1,1,1,0,0,-1.0,1,-1.0,-1.0
2238,199,7,1,43.298630,1,62.0,0,1,1,0,0,0,0.0,1,-1.0,-1.0

In [70]:
dd_df = dd_df.fillna(-1)

filtered2 = dd_df[dd_df['ANGLE'] < 0]
filtered2

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
103,9,2,1,17.753425,0,59.0,1,1,0,0,0,0,-1.0,1,-1.0,-1.0
1020,85,8,0,45.961644,0,60.0,1,1,0,0,0,0,1.0,1,-1.0,-1.0
1141,97,5,0,35.802740,1,57.0,0,1,1,0,0,0,1.0,1,-1.0,-1.0
1992,174,8,0,45.928767,0,67.0,1,1,1,1,0,0,-1.0,1,-1.0,-1.0
2238,199,7,1,43.298630,1,62.0,0,1,1,0,0,0,0.0,1,-1.0,-1.0

## Analysis of AREA and ANGLE missing data

Good thing: area and angle are missing in the same ID's! :D

In [71]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 9]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
100,9,0,0,0.000000,0,59.0,0,1,1,0,0,0,0.0,1,9.610,115.0
101,9,0,1,0.000000,0,59.0,0,1,0,0,0,0,0.0,1,6.707,16.0
102,9,1,1,14.235616,0,59.0,1,1,0,0,0,0,0.0,1,9.314,8.0
103,9,2,1,17.753425,0,59.0,1,1,0,0,0,0,-1.0,1,-1.000,-1.0
104,9,3,1,19.561644,0,59.0,1,1,0,0,0,0,0.0,1,9.988,6.0
105,9,4,1,24.789041,0,59.0,1,1,0,0,0,0,0.0,1,11.211,62.0
106,9,5,1,30.378082,0,59.0,1,1,0,0,0,0,0.0,1,12.599,24.0
107,9,6,1,37.676712,0,59.0,1,1,0,0,0,0,0.0,1,14.418,34.0
108,9,7,1,42.279452,0,59.0,1,1,0,0,0,0,0.0,1,11.782,102.0

In [72]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 85]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
1012,85,0,0,0.000000,0,60.0,1,1,0,0,0,0,0.0,1,3.250,0.0
1013,85,1,0,5.687671,0,60.0,1,1,0,0,0,0,0.0,1,2.000,0.0
1014,85,2,0,14.432877,0,60.0,1,1,0,0,0,0,0.0,1,3.067,0.0
1015,85,3,0,18.641096,0,60.0,1,1,0,0,0,0,0.0,1,2.880,0.0
1016,85,4,0,24.460274,0,60.0,1,1,0,0,0,0,0.0,1,3.467,0.0
1017,85,5,0,30.673973,0,60.0,1,1,0,0,0,0,1.0,1,3.507,0.0
1018,85,6,0,38.268493,0,60.0,1,1,0,0,0,0,1.0,1,3.700,0.0
1019,85,7,0,41.950685,0,60.0,1,1,0,0,0,0,1.0,1,4.040,4.0
1020,85,8,0,45.961644,0,60.0,1,1,0,0,0,0,1.0,1,-1.000,-1.0
1021,85,9,0,47.243836,0,60.0,1,1,0,0,0,0,1.0,1,4.707,0.0
1022,85,10,0,53.687671,0,60.0,1,1,0,0,0,0,1.0,1,3.160,0.0

In [73]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 97]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
1136,97,0,0,0.000000,1,57.0,0,1,1,0,0,0,1.0,1,9.350,0.0
1137,97,1,0,9.205479,1,57.0,0,1,1,0,0,0,1.0,1,11.355,0.0
1138,97,2,0,12.230137,1,57.0,0,1,1,0,0,0,1.0,1,11.608,0.0
1139,97,3,0,18.706849,1,57.0,0,1,1,0,0,0,1.0,1,9.609,0.0
1140,97,4,0,31.298630,1,57.0,0,1,1,0,0,0,1.0,1,11.806,6.0
1141,97,5,0,35.802740,1,57.0,0,1,1,0,0,0,1.0,1,-1.000,-1.0
1142,97,6,0,39.649315,1,57.0,0,1,1,0,0,0,1.0,1,10.840,62.0

In [74]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 174]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
1984,174,0,0,0.000000,0,67.0,1,1,1,0,0,0,0.0,1,0.35,0.0
1985,174,1,0,5.983562,0,67.0,1,1,1,0,0,0,0.0,1,0.45,0.0
1986,174,2,0,11.934247,0,67.0,1,1,1,0,0,0,0.0,1,0.70,0.0
1987,174,3,0,17.917808,0,67.0,1,1,1,0,0,0,0.0,1,0.35,0.0
1988,174,4,0,23.901370,0,67.0,1,1,1,0,0,0,0.0,1,0.13,0.0
1989,174,5,0,30.542466,0,67.0,1,1,1,0,0,0,0.0,1,0.40,0.0
1990,174,6,0,36.295890,0,67.0,1,1,1,1,0,0,0.0,1,0.50,0.0
1991,174,7,0,41.326027,0,67.0,1,1,1,1,0,0,0.0,1,0.69,0.0
1992,174,8,0,45.928767,0,67.0,1,1,1,1,0,0,-1.0,1,-1.00,-1.0
1993,174,9,0,46.717808,0,67.0,1,1,1,1,0,0,0.0,1,0.50,0.0
1994,174,10,0,53.884932,0,67.0,1,1,1,1,0,0,0.0,1,0.50,0.0

In [75]:
elements = [9, 85, 97, 174, 199]

dd_df[dd_df['ID'] == 199]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
2231,199,0,1,0.000000,1,62.0,0,1,1,0,0,0,0.0,1,0.800,0.0
2232,199,1,1,6.016438,1,62.0,0,1,1,0,0,0,0.0,1,1.200,0.0
2233,199,2,1,13.084932,1,62.0,0,1,1,0,0,0,0.0,1,1.470,0.0
2234,199,3,1,19.298630,1,62.0,0,1,1,0,0,0,0.0,1,2.123,0.0
2235,199,4,1,25.315068,1,62.0,0,1,1,0,0,0,0.0,1,2.977,0.0
2236,199,5,1,31.561644,1,62.0,0,1,1,0,0,0,0.0,1,3.843,0.0
2237,199,6,1,38.926027,1,62.0,0,1,1,0,0,0,0.0,1,4.617,0.0
2238,199,7,1,43.298630,1,62.0,0,1,1,0,0,0,0.0,1,-1.000,-1.0
2239,199,8,1,49.380822,1,62.0,0,1,1,0,0,0,0.0,1,3.375,0.0
2240,199,9,1,53.786301,1,62.0,0,1,1,0,0,0,0.0,1,3.587,0.0

## Analysis of the REL missing values

From this analysis, 3 relevant things:

- There are 8 patients with missing values in REL: 9, 20, 151, 174, 177, 179, 183, 243
- There are patients with measurements in only one hand, others in both hands and others that stopped the follow-up for only 1 hand.
- Sometimes they report to have a relative with DD in the middle of the follow up, and in the next follow up they say that they do not have. This is clearly an inconsistency we should fix. There are 30 with this inconsistency!!

### Possible solution:

- Replace "manually". This is more an inconsistency than a missing value problem.

In [26]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 9]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
100,9,0,0,0.000000,0,59.0,0,1,1,0,0,0,0.0,1,9.610,115.0
101,9,0,1,0.000000,0,59.0,0,1,0,0,0,0,0.0,1,6.707,16.0
102,9,1,1,14.235616,0,59.0,1,1,0,0,0,0,0.0,1,9.314,8.0
103,9,2,1,17.753425,0,59.0,1,1,0,0,0,0,NaN,1,NaN,NaN
104,9,3,1,19.561644,0,59.0,1,1,0,0,0,0,0.0,1,9.988,6.0
105,9,4,1,24.789041,0,59.0,1,1,0,0,0,0,0.0,1,11.211,62.0
106,9,5,1,30.378082,0,59.0,1,1,0,0,0,0,0.0,1,12.599,24.0
107,9,6,1,37.676712,0,59.0,1,1,0,0,0,0,0.0,1,14.418,34.0
108,9,7,1,42.279452,0,59.0,1,1,0,0,0,0,0.0,1,11.782,102.0

In [27]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 20]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
188,20,0,0,0.000000,1,57.0,1,1,0,0,0,0,1.0,0,0.000,0.0
189,20,1,0,6.213699,1,57.0,1,1,0,0,0,0,1.0,1,0.300,0.0
190,20,2,0,12.263014,1,57.0,1,1,0,0,0,0,1.0,1,0.340,0.0
191,20,3,0,18.443836,1,57.0,1,1,0,0,0,0,1.0,1,0.275,0.0
192,20,4,0,24.197260,1,57.0,1,1,0,0,0,0,1.0,1,1.480,0.0
193,20,5,0,30.180822,1,57.0,1,1,0,0,0,0,1.0,1,1.030,0.0
194,20,6,0,35.473973,1,57.0,1,1,0,0,0,0,1.0,1,1.340,0.0
195,20,7,0,41.457534,1,57.0,1,1,0,0,0,0,NaN,1,1.270,0.0
196,20,8,0,49.282192,1,57.0,1,1,0,0,0,0,1.0,1,1.137,0.0
197,20,9,0,53.424658,1,57.0,1,1,0,0,0,0,1.0,1,1.563,0.0

In [28]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 151]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
1719,151,0,0,0.000000,0,75.0,1,1,0,0,0,0,0.0,1,4.723,10.0
1720,151,0,1,0.000000,0,75.0,1,1,0,0,0,0,0.0,1,2.660,35.0
1721,151,1,0,4.964384,0,75.0,1,1,0,0,0,0,0.0,1,3.760,14.0
1722,151,1,1,4.964384,0,75.0,1,1,0,0,0,0,0.0,1,4.567,42.0
1723,151,2,0,10.882192,0,75.0,1,1,0,0,0,0,0.0,1,4.810,16.0
1724,151,2,1,10.882192,0,75.0,1,1,0,0,0,0,0.0,1,4.290,0.0
1725,151,3,0,16.865753,0,75.0,1,1,0,0,0,0,0.0,1,4.875,16.0
1726,151,3,1,16.865753,0,75.0,1,1,0,0,0,0,0.0,1,3.850,52.0
1727,151,4,0,22.849315,0,75.0,1,1,0,0,0,0,0.0,1,5.195,0.0
1728,151,4,1,22.849315,0,75.0,1,1,0,0,0,0,0.0,1,3.187,64.0
1729,151,5,0,25.315068,0,75.0,1,1,0,0,0,0,NaN,1,5.830,0.0
1730,151,5,1,25.315068,0,75.0,1,1,0,0,0,0,NaN,1,4.417,62.0
1731,151,6,0,28.142466,0,75.0,1,1,0,0,0,0,0.0,1,5.980,10.0
1732,151,7,0,34.126027,0,75.0,1,1,0,0,0,0,0.0,1,6.465,18.0
1733,151,8,0,40.142466,0,75.0,1,1,0,0,0,0,0.0,1,6.985,14.0
1734,151,9,0,46.553425,0,75.0,1,1,0,0,0,0,0.0,1,6.250,14.0

In [29]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 174]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
1984,174,0,0,0.000000,0,67.0,1,1,1,0,0,0,0.0,1,0.35,0.0
1985,174,1,0,5.983562,0,67.0,1,1,1,0,0,0,0.0,1,0.45,0.0
1986,174,2,0,11.934247,0,67.0,1,1,1,0,0,0,0.0,1,0.70,0.0
1987,174,3,0,17.917808,0,67.0,1,1,1,0,0,0,0.0,1,0.35,0.0
1988,174,4,0,23.901370,0,67.0,1,1,1,0,0,0,0.0,1,0.13,0.0
1989,174,5,0,30.542466,0,67.0,1,1,1,0,0,0,0.0,1,0.40,0.0
1990,174,6,0,36.295890,0,67.0,1,1,1,1,0,0,0.0,1,0.50,0.0
1991,174,7,0,41.326027,0,67.0,1,1,1,1,0,0,0.0,1,0.69,0.0
1992,174,8,0,45.928767,0,67.0,1,1,1,1,0,0,NaN,1,NaN,NaN
1993,174,9,0,46.717808,0,67.0,1,1,1,1,0,0,0.0,1,0.50,0.0
1994,174,10,0,53.884932,0,67.0,1,1,1,1,0,0,0.0,1,0.50,0.0

In [30]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 177]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
1995,177,0,0,0.000000,0,66.0,1,1,0,0,0,0,NaN,1,13.608,0.0
1996,177,0,1,0.000000,0,66.0,1,1,0,0,0,0,NaN,1,6.630,0.0
1997,177,1,0,6.838356,0,66.0,1,1,0,0,0,0,NaN,1,10.303,31.0
1998,177,1,1,6.838356,0,66.0,1,1,0,0,0,0,NaN,1,8.629,35.0
1999,177,2,0,12.394521,0,66.0,1,1,0,0,0,0,0.0,1,12.626,52.0
2000,177,2,1,12.394521,0,66.0,1,1,0,0,0,0,0.0,1,8.147,50.0
2001,177,3,0,18.378082,0,66.0,1,1,0,0,0,0,1.0,1,13.210,88.0
2002,177,3,1,18.378082,0,66.0,1,1,0,0,0,0,1.0,1,9.016,32.0
2003,177,4,0,23.868493,0,66.0,1,1,0,0,0,0,1.0,1,12.155,152.0

In [31]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 179]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
2013,179,0,0,0.000000,0,43.0,1,1,0,0,0,0,0.0,1,2.350,0.0
2014,179,0,1,0.000000,0,43.0,1,1,1,0,0,0,0.0,1,4.600,65.0
2015,179,1,0,6.016438,0,43.0,1,1,0,0,0,0,0.0,1,2.700,0.0
2016,179,1,1,6.016438,0,43.0,1,1,1,0,0,0,0.0,1,3.350,60.0
2017,179,2,0,12.230137,0,43.0,1,1,0,0,0,0,0.0,1,1.500,0.0
2018,179,2,1,12.230137,0,43.0,1,1,1,0,0,0,0.0,1,3.660,54.0
2019,179,3,0,18.213699,0,43.0,1,1,0,0,0,0,0.0,1,1.450,0.0
2020,179,3,1,18.213699,0,43.0,1,1,1,0,0,0,0.0,1,3.380,58.0
2021,179,4,0,24.328767,0,43.0,1,1,0,0,0,0,1.0,1,1.783,0.0
2022,179,4,1,24.328767,0,43.0,1,1,1,0,0,0,1.0,1,3.350,38.0
2023,179,5,0,30.147945,0,43.0,1,1,0,0,0,0,0.0,1,4.260,0.0
2024,179,5,1,30.147945,0,43.0,1,1,1,0,0,0,0.0,1,5.555,26.0
2025,179,6,0,36.821918,0,43.0,1,1,0,0,0,0,NaN,1,4.420,0.0
2026,179,6,1,36.821918,0,43.0,1,1,1,0,0,0,NaN,1,5.537,44.0
2027,179,7,0,41.424658,0,43.0,1,1,0,0,0,0,NaN,1,5.630,0.0
2028,179,7,1,41.424658,0,43.0,1,1,1,0,0,0,NaN,1,7.200,20.0
2029,179,8,0,47.408219,0,43.0,1,1,0,0,0,0,NaN,1,5.947,8.0
2030,179,8,1,47.408219,0,43.0,1,1,1,0,0,0,NaN,1,7.910,36.0
2031,179,9,0,54.016438,0,43.0,1,1,0,0,0,0,NaN,1,6.460,16.0
2032,179,9,1,54.016438,0,43.0,1,1,1,0,0,0,NaN,1,5.797,36.0

In [32]:
# Patients with NaN in REL column: 9, 20, 151, 174, 177, 179, 183, 243

dd_df[dd_df['ID'] == 183]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
2073,183,0,1,0.000000,0,68.0,1,1,1,0,0,0,0.0,1,0.000,0.0
2074,183,1,1,5.884932,0,68.0,1,1,1,0,0,0,0.0,1,3.850,0.0
2075,183,2,1,12.065753,0,68.0,1,1,1,0,0,0,0.0,1,4.438,0.0
2076,183,3,1,18.509589,0,68.0,1,1,1,0,0,0,0.0,1,5.617,0.0
2077,183,4,1,24.295890,0,68.0,1,1,1,0,0,0,0.0,1,7.350,0.0
2078,183,5,1,34.849315,0,68.0,1,1,1,0,0,0,NaN,1,7.228,0.0
2079,183,6,1,41.523288,0,68.0,1,1,1,0,0,0,NaN,1,7.337,6.0
2080,183,7,1,54.871233,0,68.0,1,1,1,0,0,0,0.0,1,5.800,4.0

In [33]:
dd_df[dd_df['ID'] == 243]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
2698,243,0,0,0.000000,0,63.0,0,1,0,0,0,0,0.0,1,3.520,0.0
2699,243,1,0,5.852055,0,63.0,0,1,0,0,0,0,0.0,1,7.867,0.0
2700,243,2,0,11.934247,0,63.0,0,1,0,0,0,0,0.0,1,8.230,0.0
2701,243,3,0,17.950685,0,63.0,0,1,0,0,0,0,0.0,1,7.115,0.0
2702,243,4,0,23.901370,0,63.0,0,1,0,0,0,0,0.0,1,6.332,0.0
2703,243,5,0,30.641096,0,63.0,0,1,0,0,0,0,NaN,1,8.905,0.0
2704,243,6,0,36.328767,0,63.0,0,1,0,0,0,0,0.0,1,8.938,0.0
2705,243,7,0,42.312329,0,63.0,0,1,0,0,0,0,0.0,1,10.167,0.0
2706,243,8,0,47.243836,0,63.0,0,1,0,0,0,0,0.0,1,10.563,0.0
2707,243,9,0,54.410959,0,63.0,0,1,0,0,0,0,0.0,1,11.559,6.0

## Analysis of the ID's with inconsistencies in the REL field (false and true at the same time)

I analyzed one by one the suspicious elements.

### Results
- 2: Only one followup with REL = 0. FIX by setting all to 1.
- 9: Has one missing value. FIX by setting all to 0.
- 12: Hard to say. Initially, it is set to 0, then there is one "outlier" at FU=3. Also at the end the patient reports REL=1. Maybe at the end a relative got the disease. CHECK IN DETAIL.
- 20: Just a missing value problem. FIX by setting all to 1.
- 24: Hard to say. In the last FU it reports REL=1. All others are REL=0.
- 32: Hard to say. One ontlier in follow yp 1. CHECK IN DETAIL.
- 35: No real problem, but better to CHECK IN DETAIL.
- 38: FIX: I would say set all to 1.
- 67: FIX: I would say set all to 0.
- 85: Looks ok... But with 2 values
- 93: One outlier at the beginning. FIX: Set first value to 0.
- 104: Not sure if the first one is outlier :(. CHECK IN DETAIL.
- 108: I would say set all to 0.
- 130: I would say it is ok, but has to values :(
- 151: Just one missing vlaue. FIX: Set all to 0.
- 154: Small dataset. Set all to 0.
- 168: One different value at FU=0. FIX: I would say set all to 0.
- 174: Just one missing value. Set all to 0.
- 177: Missing values + 0 and 1. I would say to set the missing values to 0.
- 179: HARD TO SAY. Check in detail.
- 182: Outlier. Set all to 1.
- 183: Just missing value. SET all to 0.
- 218: I would say to set all to 1.
- 221: Looks ok, but 2 values :(
- 223: I would say to set all to 0. CHECK.
- 235: Looks ok. Maybe set all to 1. CHECK!
- 237: Looks ok, but two values :(
- 243: Missing value. FIX: set all to 0.
- 247: NO IDEA! :(
- 248: I would say set all to 0. CHECK.

In [64]:
elements = [2, 9, 12, 20, 24, 32, 35, 38, 67, 85, 93, 104, 108, 130, 151, 154, 168, 174, 177, 179, 182, 183,
           218, 221, 223, 235, 237, 243, 247, 248]

dd_df[dd_df['ID'] == 248]

,ID,FU,Hand,MONTH,SEX,AGE0,SMOKE,ALC,INJ,DIA,EPI,LIV,REL,DD,AREA,ANGLE
2749,248,0,0,0.000000,1,77.0,0,1,1,0,0,0,1.0,0,0.000,0.0
2750,248,0,1,0.000000,1,77.0,0,1,1,0,0,0,1.0,1,1.360,0.0
2751,248,1,0,7.167123,1,77.0,0,1,1,0,0,0,0.0,0,0.000,0.0
2752,248,1,1,7.167123,1,77.0,0,1,1,0,0,0,0.0,1,1.430,0.0
2753,248,2,0,30.378082,1,77.0,0,1,1,0,0,0,0.0,1,0.850,0.0
2754,248,2,1,30.378082,1,77.0,0,1,1,0,0,0,0.0,1,1.907,0.0